# Generated by Django 5.2.15 on 2026-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=2)),
                ('price', models.FloatField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='routing_sta_lat_52d4bd_idx'), models.Index(fields=['state'], name='routing_sta_state_810e58_idx')],
            },
        ),
    ]
